- name: varnish-restart
  service: >
    name={{ service_varnish }}
    state=restarted

- name: varnish-start
  service: >
    name={{ service_varnish }}
    state=started

- name: varnish-stop
  service: >
    name={{ service_varnish }}
    state=stopped
